// List of sample products for autocomplete
export const PRODUCTS = [
	{ id: 1, name: "ลูกเกด", price: 36 },
	{ id: 2, name: "หมูหยอง", price: 36 },
	{ id: 3, name: "หยองเกด", price: 36 },
	{ id: 4, name: "หยองพริกเผา", price: 36 },
	{ id: 5, name: "รวมมิตร", price: 36 },
	{ id: 6, name: "ผลไม้รวม", price: 36 },
	{ id: 7, name: "เนยสด", price: 36 },
	{ id: 8, name: "เผือก", price: 36 },
	{ id: 9, name: "สังขยา", price: 36 },
	{ id: 10, name: "มันม่วง", price: 36 },
	{ id: 11, name: "ถั่วแดง", price: 36 },
	{ id: 12, name: "งาดำ", price: 36 },
	{ id: 13, name: "ครีมถั่วเหลือง", price: 36 },
	{ id: 14, name: "สับปะรดลูกเกด", price: 36 },
	{ id: 15, name: "ช็อคโกแลต", price: 36 },
	{ id: 16, name: "ช็อคโกแลตลูกเกด", price: 36 },
	{ id: 17, name: "ลูกเกดไข่เค็ม", price: 38 },
	{ id: 18, name: "หมูหยองไข่เค็ม", price: 38 },
	{ id: 19, name: "สังขยาไข่เค็ม", price: 38 },
	{ id: 20, name: "ถั่วเขียวไข่เค็ม", price: 38 },
	{ id: 21, name: "ฝอยทอง", price: 38 },
	{ id: 22, name: "ฝอยทองลูกเกด", price: 38 },
	{ id: 23, name: "ฝอยทองช็อคโกแลต", price: 38 },
	{ id: 24, name: "เค้กกล้วย", price: 330 },
];
